import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './styles/global.scss'
import { StoreProvider } from './providers/StoreProvider'
import { Header } from '@widgets/Header/ui/Header'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Bai Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  )
}
